FROM golang:1.17-alpine as build

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

ADD . /build/

RUN go mod tidy
# Move to registry service directory
WORKDIR /build/cmd/registryservice

RUN mkdir -p /dist

RUN go build -o /dist .

##
## Deploy
##

FROM alpine:latest

WORKDIR /app

COPY --from=build /dist .

EXPOSE 3000

CMD [ "./registryservice" ]